project:
  type: book
  output-dir: docs

book:
  title: "ThesisBook"
  author: "Mélanie"
  date: "3/15/2023"
  chapters:
    - index.qmd
    - 2_intro.qmd
    - 3_motivation.qmd
    - 4_convecDiff.qmd
    - 5_solverExploration.qmd
    - 6_reinforcementBasic.qmd
    - 7_policyGradient.qmd
    - 8_implementation.qmd
    - 9_summary.qmd
    - 10_references.qmd

bibliography: references.bib
csl: ieee.csl

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
    pdf-engine: xelatex
    geometry: 
    - top=30mm
    - left=20mm
    number-sections: true


