project:
  type: book
  output-dir: docs

book:
  title: "ThesisBook"
  author: "Mélanie"
  date: "3/15/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - motivation.qmd
    - testEqIntro.qmd
    - solverExploration.qmd
    - reinforcementBasic.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



